### ISSUE TITLE
I must use asset-map:compile to see modification

### ISSUE THREAD

**Issue by LewisSama** [SymfonyCasts/tailwind-bundle#77]
Hi ! 

I'm using the template from [dunglas/symfony-docker](https://github.com/dunglas/symfony-docker).  I followed the instruction to build/launch my container and installed the bare minimum according to documentation:

[Twig](https://symfony.com/components/Twig%20Bundle):
- `symfony/twig-bundle` 

[Asset-mapper](https://symfony.com/doc/current/frontend/asset_mapper.html):
- `symfony/asset-mapper` 
- `symfony/asset `
- `symfony/twig-pack`

[Tailwindbundle](https://symfony.com/bundles/TailwindBundle/current/index.html): 
- `symfonycasts/tailwind-bundle`

After installing those according to documentation, i created a simple controller to use my twig file but i encounter an error: 
`An exception has been thrown during the rendering of a template ("Built Tailwind CSS file does not exist: run "php bin/console tailwind:build" to generate it").`

Even after running `php bin/console tailwind:build`, the error persists. 
The only way to stop this error is to compile using `asset-map:compile`.

Afterward, every change i've made and built are not applied even when i use the `--poll`  and i must rerun `asset-map:compile` to see any modification.

As it is very inconvenient to use `asset-map:compile` at every change, i wanted to know if there is anyway to make my `tailwind:build --watch` works.

Also, it's my first issue on GitHub so if there is any modification to make or precision, please tell me.

**Comment by weaverryan** [comment]
Could be related: https://github.com/SymfonyCasts/tailwind-bundle/commit/81c9e6ff2bb1a95e67fc6af04ca87fccdcf55aa4 - make sure (for now) that Tailwind 3 is being downloaded

**Comment by Dameen-Rainer** [comment]
I'm facing similar problem, when I add or edit classes in my 'main/homepage.html.twig' template,  tailwind:build -w doesn't show any rebuilding changes & the browser doesn't reflect those classes' changes as well. 
I always have to make some changes to another template  classes, so tailwind:build -w and browser can reflect those changes.

**Comment by kbond** [comment]
Is everyone experiencing this issue using docker?

**Comment by thinway** [comment]
yes, I'm using docker

**Comment by MatthieuLeVerger** [comment]
I'm facing the exact same issue, also using Tailwind v3.4.17, did one of you found a solution except using asset-map:compile ?

**Comment by Sh3nl0ng** [comment]
I'm using the https://github.com/dunglas/symfony-docker boilerplate, and experiencing this issue.

**Comment by kbond** [comment]
Ok, pretty sure this issue is docker-specific. I don't use this in docker myself so I'll need some help here.

**Comment by Sh3nl0ng** [comment]
For my case, this appears to be an issue with the `/var` folder not being mapped into the container by default.

By adding `./var:/app/var` to my `volumes` definition in the `compose.override.yaml` I was able to resolve this issue.

```yaml
# Development environment override
services:
  php:
    build:
      context: .
      target: frankenphp_dev
    volumes:
      - ./:/app
      - ./frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./frankenphp/conf.d/20-app.dev.ini:/usr/local/etc/php/app.conf.d/20-app.dev.ini:ro
      # If you develop on Mac or Windows you can remove the vendor/ directory
      #  from the bind-mount for better performance by enabling the next line:
      # - /app/vendor
      - ./var:/app/var
    environment:
      MERCURE_EXTRA_DIRECTIVES: demo
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    tty: true

###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "3306"
###< doctrine/doctrine-bundle ###
```
